Repository teamSilabuz/projectunidad_backend, pull requests merged in 2023-02, with the labels that each got.

#7 Feature/envio email
  package.json
  src/components/boot/controller.ts
  src/components/boot/index.ts
  src/config/env.ts
  src/interfaces/smsContext.ts
  src/services/index.ts
  src/services/sgMail/index.ts
Labels: enhancement, create

#8 Feature/2 login
  package.json
  src/components/user/controller.ts
  src/components/user/index.ts
  src/config/env.ts
  src/libs/helpers.ts
  src/libs/jwt.ts
Labels: enhancement, create

#9 Feature/3 update user
  src/components/user/controller.ts
  src/components/user/index.ts
Labels: enhancement, create

#11 Feature contrasena externa
  prisma/schema.prisma
  src/components/credencial/controller.ts
  src/components/credencial/index.ts
  src/components/index.ts
  src/libs/helpers.ts
  src/routes/index.ts
  src/services/index.ts
Labels: enhancement, create

#12 feat: implementación test del component boot_sms_email
  package.json
  src/components/boot/controller.ts
  src/services/sgMail/index.ts
  test/bootgmail.test.ts
  test/bootsms.test.ts
Labels: enhancement

#13 feat: Se ha completado los test del component boot
  src/components/boot/controller.ts
  test/bootgmail.test.ts
  test/bootsms.test.ts
Labels: enhancement

#14 feat: se ha corrigido los test
  test/bootgmail.test.ts
  test/bootsms.test.ts
Labels: corrección

#15 Estructura inicial del Readme.md
  README.md
Labels: enhancement

#16 Feature/4 password credenciales externas
  src/components/user/controller.ts
  src/components/user/index.ts
Labels: enhancement, create

#17 credenciales readme
  README.md
  src/components/credencial/controller.ts
  src/components/credencial/index.ts
  test/crendecial.test.ts
Labels: documentation, enhancement

#18 corrigio errores del test
  test/crendecial.test.ts
Labels: corrección

#21 feat: libreria de encriptacion y desencriptacion implementada
  package.json
  src/config/env.ts
  src/libs/endecrypt.ts
  src/libs/helpers.ts
Labels: enhancement

#22 fetch credentials from gestor
  src/components/gestor/controller.ts
  src/components/gestor/index.ts
  src/components/index.ts
  src/routes/index.ts
Labels: enhancement

#23 test de gestor
  test/gestor.test.ts
Labels: enhancement

#25 request del perfil del usuario implementado
  src/components/user/controller.ts
  src/components/user/index.ts
Labels: enhancement

#26 Feature/5 testeo
  src/components/user/controller.ts
  test/userlogin.test.ts
  test/userregistro.test.ts
  test/userupdatepassexterno.test.ts
  test/userupdateuser.test.ts
Labels: create

#27 feat: corrigiendo eel method request del perfil user
  src/components/user/controller.ts
  src/components/user/index.ts
Labels: bug, enhancement

#29 Release
  .env.example
  .github/workflows/tester-actions.yml
  .vercelignore
  README.md
  nodemon.json
  package.json
  prisma/schema.prisma
  src/app.ts
  src/components/boot/controller.ts
  src/components/boot/index.ts
  src/components/credencial/controller.ts
  src/components/credencial/index.ts
  src/components/gestor/controller.ts
  src/components/gestor/index.ts
  src/components/index.ts
  src/components/user/controller.ts
  src/components/user/index.ts
  src/config/env.ts
  src/datasource/index.ts
  src/interfaces/smsContext.ts
  src/libs/endecrypt.ts
  src/libs/helpers.ts
  src/libs/jwt.ts
  src/routes/index.ts
  src/services/index.ts
  src/services/sgMail/index.ts
  src/services/twilio/index.ts
  test/bootgmail.test.ts
  test/bootsms.test.ts
  test/crendecial.test.ts
  test/gestor.test.ts
  test/userlogin.test.ts
  test/userregistro.test.ts
  test/userupdatepassexterno.test.ts
  test/userupdateuser.test.ts
  tsconfig.build.json
  vercel.json
Labels: create

#30 Feature/10 mejorando workflows
  .github/workflows/tester-actions.yml
Labels: enhancement
